### PR TITLE
Make config parameters optional

### LINKED ISSUE #105: Config parameters that have defaults should be optional
When a config parameter has a default value, the user should be able to optionally omit it from the config file.

For example, since `playgroundEnabled` has a default value of true, the user need not specify it.

Currently, the server throws an exception for missing parameters.

### PR DESCRIPTION
**Pull request by rr83019**
closes #105

### CODE REVIEW

File: src/main/scala/lc/core/config.scala [hunk 1]
```diff
@@ -71,7 +84,7 @@ class Config(configFilePath: String) {
         (AttributesEnum.CAPTCHA_EXPIRY_TIME_LIMIT.toString -> 5) ~
         (AttributesEnum.THROTTLE.toString -> 1000) ~
         (AttributesEnum.THREAD_DELAY.toString -> 2) ~
-        (AttributesEnum.PLAYGROUND_ENABLED.toString -> true) ~
+        (AttributesEnum.PLAYGROUND_ENABLED.toString -> "true") ~
```
Comment (hrj) [inline src/main/scala/lc/core/config.scala:87]: Hmm.. changing the type will break existing configurations.

How about using the `extract` function using a case class. Something like:

```
case class ConfigFields(
  port: Option[Int],
  address: Option[String],
  playgroundEnabled: Option[Boolean],
  ...
)

val fields = configJson.extract[ConfigFields]

val port = fields.port.getOrElse(8888)
val address = fields.address.getOrElse("0.0.0.0")
val playgroundEnabled = fields.playgroundEnabed.getOrElse(true)
```

**Comment by hrj** [comment]
I was able to get it to work after some trial and error:

When using Option for extraction, we need to use java types instead of scala types. So this works:

```scala
case class ConfigField(
                        port: Option[Integer],
                        address: Option[String],
                        throttle: Option[Integer],
                        seed: Option[Integer],
                        captchaExpiryTimeLimit: Option[Integer],
                        threadDelay: Option[Integer],
                        boolTest: Option[java.lang.Boolean],
                        corsHeader: Option[String],
                        maxAttempts: Option[Integer]
                      )
```

Needs to be converted to the correct Scala type later. So I did this hack:

```
 case class ConfigField(
  port: Option[Integer],
  address: Option[String],
  throttle: Option[Integer],
  seed: Option[Integer],
  captchaExpiryTimeLimit: Option[Integer],
  threadDelay: Option[Integer],
  boolTest: Option[java.lang.Boolean],
  corsHeader: Option[String],
  maxAttempts: Option[Integer]
) {
  val portInt = port.map(_ + 0)
  val boolTestBoolean = boolTest.map(_ || true)
}

...

  val fields = configJson.extract[ConfigField]

  val port1: Int = fields.portInt.getOrElse(8888)
  val address1: String = fields.address.getOrElse("0.0.0.0")
  val boolTest: Boolean = fields.boolTestBoolean.getOrElse(true)

```

File: src/main/scala/lc/core/models.scala [hunk 2]
```diff
@@ -18,3 +18,24 @@ case class CaptchaConfig(
...
+    ){
+  lazy val portInt: Option[Int] = mapInt(port)
+  lazy val throttleInt: Option[Int] = mapInt(throttle)
+  lazy val seedInt: Option[Int] = mapInt(seed)
+  lazy val captchaExpiryTimeLimitInt: Option[Int] = mapInt(captchaExpiryTimeLimit)
+  lazy val threadDelayInt: Option[Int] = mapInt(threadDelay)
+  lazy val maxAttemptsInt: Option[Int] = mapInt(maxAttempts)
+  lazy val playgroundEnabledBool: Option[Boolean] = playgroundEnabled.map(_ || true)
+
+  private val mapInt = (x: Option[Integer]) => x.map(_ + 0)
```
Comment (hrj) [inline src/main/scala/lc/core/models.scala:40]: Just for readability, can you make it a normal function?

File: src/main/scala/lc/core/config.scala (hunk 1 above)
Comment (hrj) [reply src/main/scala/lc/core/config.scala:76]: Should this be string?

**Review by hrj — CHANGES_REQUESTED** [review]
